---
# because we use ansible-pull and include_role (dynamic includes), handlers do not work

# - name: restart apache2
#   systemd:
#     name: apache2
#     state: restarted

# - name: restart jupyterhub
#   systemd:
#     name: jupyterhub
#     state: restarted

- name: Update helm repo
  ansible.builtin.command:
    cmd: helm repo update
  environment: "{{ proxy_env | default(omit) }}"
